import Head from 'next/head'
import React, { useEffect } from 'react';
import Image from 'next/image';
import gardenPizz from "@/public/assets/images/gardenPizz.png"
import carte from "@/public/assets/images/carte.png"
import logo1 from '@/public/assets/images/logo1.png'
import logo2 from '@/public/assets/images/logo2.png'
import logo3 from '@/public/assets/images/logo3.png'
import logo4 from '@/public/assets/images/logo4.png'
import logo5 from '@/public/assets/images/logo5.png'
import logo6 from '@/public/assets/images/logo6.png'
import logo7 from '@/public/assets/images/logo7.png'
import logo8 from '@/public/assets/images/logo8.png'
import logo9 from '@/public/assets/images/logo9.png'
export default function Home() {

  return (
    <>
      <Head>
        <title>GardenPizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/engine.ico" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
      </Head>
      <section id="accueil absolute">
        <header className='py-2 px-4 lg:fixed lg:px-14 top-0 left-0 w-full flex justify-between items-center z-50'>
          <a href="/" class="nom">
            <Image src={gardenPizz} width={100} height={100} />
          </a>
          <ul className='flex space-x-10 items-center text-white '>
            <li><a className='w-full hover:text-[#EB3A3A]' href="#accueil">Accueil</a></li>
            <li><a className='w-full  hover:text-[#EB3A3A]' href="#carte">La carte</a></li>
            <li><a className='w-full  hover:text-[#EB3A3A]' href="#apropos">A propos</a></li>
          </ul>
        </header>


        <div className="relative min-h-screen bg-cover bg-center" style={{ backgroundImage: `url('/assets/images/hero.png')` }}>
          {/* Superposition noire avec transparence */}
          <div className="absolute inset-0 bg-black opacity-70"></div> {/* Ce div crée un filtre noir */}

          <div class="flex px-4 md:px-8 lg:px-0 items-center text-center justify-center absolute inset-0 ">
            <div>
              <Image src={gardenPizz} className='w-[40rem]' />
              <span className=' text-9xl text-[#1AF742] font-[Inspiration] '>
                2=3
              </span>
              <p className=' text-4xl'> <span className='text-[#7FFF00]'>Pour deux pizzas achetées,</span> <br />
                <span className='text-[#EB3A3A]'>la troisieme est offerte</span></p>
              <div className='flex items-center justify-center mt-10'>

                <a id="numTel" href="tel:07 68 78 18 26"
                  class="shadow-none w-fit rounded-md border-none flex items-center space-x-2 text-sm px-4 py-2.5
                   font-medium text-white bg-[#EC5F34] transition duration-150 ease-in-out">
                  <svg id="numTel" class="w-5 h-5 text-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24">
                    <path d="M798-120q-125 0-247-54.5T329-329Q229-429 174.5-551T120-798q0-18 12-30t30-12h162q14 0 25 9.5t13 22.5l26 140q2 16-1 27t-11 19l-97 98q20 37 47.5 71.5T387-386q31 31 65 57.5t72 48.5l94-94q9-9 23.5-13.5T670-390l138 28q14 4 23 14.5t9 23.5v162q0 18-12 30t-30 12Z"></path>
                  </svg>
                  <span id="numTel" class="block text-xl">07 68 78 18 26</span>
                </a>
              </div>
            </div>


          </div>
        </div>
        <div className='max-w-7xl mx-auto'>
          <div id="carte" className=' mt-20'>
            <h2 className='text-4xl text-center text-[#EC5F34] mb-5 underline'>NOTRE CARTE</h2>
            <Image src={carte} />
          </div>
          <div className='px-4 md:px-8 lg:px-0 mt-20'>
            <h2 className='text-4xl text-center text-[#EC5F34] mb-5 underline'>OU NOUS TROUVEZ</h2>
            <div className='flex items-center justify-center'>
              <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2912.523691430775!2d5.842617276532981!3d43.11452378710338!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12c90545bc6616a1%3A0xb1c82c8b92889c3!2sGarden%20Pizz!5e0!3m2!1sfr!2sfr!4v1740067112604!5m2!1sfr!2sfr"
                height="550" className='w-full rounded-md' loading="lazy" ></iframe>
            </div>
          </div>
          <div id="apropos" className='px-4 md:px-8 lg:px-0 mt-20'>
            <h2 className='text-4xl text-center text-[#EC5F34] mb-5 underline'>A propos de nous </h2>
            <div className='flex items-center justify-center'>
              <p className='text-white text-xl text-center xl:px-20'>Bienvenue sur notre site ! Nous sommes une pizzeria située à Six-Fours-les-Plages, ouverte 7 jours
                sur 7, où vous pouvez déguster nos délicieuses pizzas sur place ou profiter de notre service de
                livraison dans les communes de Six-Fours-les-Plages, Sanary-sur-Mer, Ollioules
                et La Seyne-sur-Mer.<br /><br />
                Pour vous régaler tout en faisant des économies, nous vous proposons une offre spéciale : pour l'achat de
                deux pizzas, la troisième est offerte.
                Notre équipe passionnée met un point d'honneur à vous servir des plats de qualité,
                préparés avec des ingrédients frais et savoureux.<br /><br />

                Nous vous invitons à découvrir notre menu varié et à profiter de nos services pour une expérience
                culinaire agréable.</p>
            </div>
          </div>

        </div>
        <div className="my-20">
          <div className="bg-[#EC5F34] overflow-hidden flex flex-col items-center  justify-center">
            <h3 className="bg-black rounded-b-xl text-[#EC5F34] mb-6 px-4 py-2 underline text-center text-4xl w-fit">
              NOS PARTENAIRES
            </h3>
            {/* Conteneur de défilement */}
            <div className="flex animate-marquee space-x-24">
              {/* Répéter les images pour éviter le vide */}
              <div className="flex space-x-24">
                <Image src={logo1} alt="Logo 1" className=" shrink-0 w-40 object-contain " />
                <Image src={logo2} alt="Logo 2" className=" shrink-0 w-40 object-contain " />
                <Image src={logo3} alt="Logo 3" className=" shrink-0 w-40 object-contain " />
                <Image src={logo4} alt="Logo 4" className=" shrink-0 w-40 object-contain " />
                <Image src={logo5} alt="Logo 5" className=" shrink-0 w-40 object-contain " />
                <Image src={logo6} alt="Logo 6" className=" shrink-0 w-40 object-contain " />
                <Image src={logo7} alt="Logo 7" className=" shrink-0 w-40 object-contain " />
                <Image src={logo8} alt="Logo 8" className=" shrink-0 w-40 object-contain " />
                <Image src={logo9} alt="Logo 9" className=" shrink-0 w-40 object-contain " />
                <Image src={logo1} alt="Logo 1" className=" shrink-0 w-40 object-contain " />
                <Image src={logo2} alt="Logo 2" className=" shrink-0 w-40 object-contain " />
                <Image src={logo3} alt="Logo 3" className=" shrink-0 w-40 object-contain " />
                <Image src={logo4} alt="Logo 4" className=" shrink-0 w-40 object-contain " />
                <Image src={logo5} alt="Logo 5" className=" shrink-0 w-40 object-contain " />
                <Image src={logo6} alt="Logo 6" className=" shrink-0 w-40 object-contain " />
                <Image src={logo7} alt="Logo 7" className=" shrink-0 w-40 object-contain " />
                <Image src={logo8} alt="Logo 8" className=" shrink-0 w-40 object-contain " />
                <Image src={logo9} alt="Logo 9" className=" shrink-0 w-40 object-contain " />
            
              </div>
            </div>
          </div>
        </div>


        <footer class=" bg-[#333] shadow-sm ">
          <div class="w-full text-white max-w-screen-xl mx-auto p-4 md:py-8">
            <div class="sm:flex sm:items-center sm:justify-between">
              <a href="#accueil" class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
                <Image src={gardenPizz} className='w-40' alt="Logo" />
              </a>
              <ul class="flex flex-wrap space-x-10 items-center mb-6 text-sm font-medium text sm:mb-0 dark:text-gray-400">
                <li>
                  <a href="#apropos" class="hover:underline me-4 md:me-6">A propos</a>
                </li>
                <li>
                  <a href="#carte" class="hover:underline me-4 md:me-6">La carte</a>
                </li>
              </ul>
            </div>
            <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
            <span class="block text-sm ">© 2025
              <a href="#accueil" class="hover:underline"> GardenPizz </a>.Tous droits réservés .</span>
          </div>
        </footer>
      </section>
    </>
  )
}
