import Head from 'next/head'
import React from 'react';
import Image from 'next/image';

import Hero from "@/components/Hero/layout"
import Carte from "@/components/Carte/layout"
import Localisation from "@/components/Localisation/layout"
import Apropos from "@/components/Apropos/layout"
import Carroussel from "@/components/Caroussel/layout"
import gardenPizz from "@/public/assets/images/gardenPizz.png"


export default function Home() {

  return (
    <>
      <Head>
        <title>GardenPizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/engine.ico" />
      </Head>

      <section id="accueil">
        <header className='py-2 px-4 lg:fixed lg:px-14 top-0 left-0 w-full flex justify-between items-center z-50'>
          <a href="/" className="nom">
            <Image src={gardenPizz} alt='logo garden pizz' width={100} height={100} />
          </a>
          <ul className='flex space-x-10 items-center text-white '>
            <li><a className='w-full hover:text-[#EB3A3A]' href="#accueil">Accueil</a></li>
            <li><a className='w-full  hover:text-[#EB3A3A]' href="#carte">La carte</a></li>
            <li><a className='w-full  hover:text-[#EB3A3A]' href="#apropos">A propos</a></li>
          </ul>
        </header>
        <Hero />
        <div className='max-w-7xl mx-auto'>
          <Carte />
          <Localisation />
          <Apropos />
        </div>
        <Carroussel />
      </section>
    </>
  )
}
