import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import gardenPizz from "@/public/assets/images/gardenPizz.png"
export default function mentionsLegales() {
    return (
        <div>
        <Head>
        <title>GardenPizz - mentions legales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/engine.ico" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
      </Head>
      <header className='py-2 px-4 lg:fixed lg:px-14 top-0 left-0 w-full flex justify-between items-center z-50'>
          <a href="/" className="nom">
            <Image src={gardenPizz} width={100} height={100} />
          </a>
          <ul className='flex space-x-10 items-center text-white '>
            <li><a className='w-full hover:text-[#EB3A3A]' href="/#accueil">Accueil</a></li>
            <li><a className='w-full  hover:text-[#EB3A3A]' href="/#carte">La carte</a></li>
            <li><a className='w-full  hover:text-[#EB3A3A]' href="/#apropos">A propos</a></li>
          </ul>
        </header>
        <div className='max-w-7xl text-white mx-auto'>
            <h1 className='text-center text-4xl py-10'> Mentions Légales</h1>
            <p className='mb-6'>
                <span className='underline font-medium text-xl'>1. Éditeur du site <br /> </span>
                Le site internet "GardenPizz" est édité par la société SAS CLA,
                SAS , immatriculée au RCS de
                Six fours les plages sous le numéro 98190733000014.<br />
                Siège social : 55 rue de l'Artisanat,
                83140 Six-Fours-les-PlagesResponsable de la publication : Aurélie Egea Contact : aurelie_fedele@hotmail.fr
                / 06 30 26 57 40
            </p>
            <p className='mb-6'>
            <span className='underline block  font-medium text-xl'>2. Hébergement</span>
                Le site est hébergé par OVH, dont le siège social est situé au 2 rue Kellermann, 59100 Roubaix, France.
            </p>
            <p className='mb-6'>
            <span className='underline block  font-medium text-xl'> 3. Propriété intellectuelle</span>
                L'ensemble du contenu du site (textes, images, logos, etc.) est la propriété exclusive de GardenPizz ou fait l'objet d'une autorisation d'utilisation. Toute reproduction, distribution ou modification sans autorisation est interdite.
            </p>
            <p className='mb-6'>
            <span className='underline block  font-medium text-xl'>4. Protection des données personnelles</span> Aucune donnée personnelle n'est collectée via ce site. Toutefois, pour toute demande transmise par e-mail ou téléphone, les informations communiquées seront uniquement utilisées pour traiter la demande.
            </p>
            <p className='mb-6'>
            <span className='underline block  font-medium text-xl'>5. Responsabilité</span> GardenPizz s'efforce d'assurer l'exactitude des informations publiées sur ce site, mais ne peut garantir leur exhaustivité ou mise à jour en temps réel. L'utilisateur reconnaît utiliser ces informations sous sa propre responsabilité.
            </p>
            <p className='mb-6'>
            <span className='underline block  font-medium text-xl'>6. Liens hypertextes</span> Le site peut contenir des liens vers des sites externes. GardenPizz ne peut être tenu responsable du contenu de ces sites tiers.
            </p>
            <p className='mb-6'>
            <span className='underline block  font-medium text-xl'>7. Droit applicable</span> Les présentes mentions légales sont soumises au droit français. En cas de litige, les tribunaux compétents seront ceux du ressort du siège social de GardenPizz.
            </p>
        </div>
        </div>
    )
}
